first version
numicaela/SwiftTv pull request #1
Opened 2020-02-17 13:54 UTC by numicaela

2020-03-02 15:42 UTC, ArielCongestriUala requested changes

2020-03-02 15:42 UTC, ArielCongestriUala commented on SwiftTv/Models/ModelsDTO/ShowDTO.swift
> +        self.name = (try? container.decode( String.self, forKey: .name)) ?? ""
este es el unico caso en el que son necesarios los (). En los demas no es necesario, estaria bueno que lo remuevas, por cuestion de proligidad

2020-03-02 15:42 UTC, ArielCongestriUala commented on SwiftTv/Models/ShowDTOMapping.swift
> +struct ShowDTOMapping {
Esto deberia ser una clase, todo lo que son helpers y demas es mejor que sean clases. Pero por otro lado no tiene una funcionalidad muy interesante. Por que liretalmente estas ejecutando un init. Podrias borrar este file tranquilamente

2020-03-02 15:42 UTC, ArielCongestriUala commented on SwiftTv/View/Details/DetailsViewController.swift
> +        let url = URL(string: (show.image!))
Terminalmente prohibido usar el !. Siempre usar validaciones con if let, o con guard. Pero nunca el !

2020-03-02 15:42 UTC, ArielCongestriUala commented on SwiftTv/View/Details/DetailsViewController.swift
> +extension UIImageView {
Las extensiones que van en un file aparte. a no ser que sean de la misma  clase

2020-03-02 15:42 UTC, ArielCongestriUala commented on SwiftTv/View/Details/DetailsViewController.swift
> +extension String {
Lo mismo

2020-03-02 15:42 UTC, ArielCongestriUala commented on SwiftTv/View/Menu/MenuCell/MenuCell.swift
> +        for genre in genres ?? [""] {
Esto se lo corregui a lau, habla con ella que te muestre la alternativa que le comente

2020-03-02 15:42 UTC, ArielCongestriUala commented on SwiftTv/View/Menu/MenuViewController.swift
> +        table?.rowHeight = 155
hay un metodo que cubre esta funcion y es dinamico. Trata de buscarlo e implementarlo

2020-03-02 15:42 UTC, ArielCongestriUala commented on SwiftTv/View/Menu/MenuViewController.swift
> +    _ = AF.request("http://api.tvmaze.com/shows")
las URL estara buenisimo que las tengas en un file aparte tipo una static let. Pensalo, y si no se te ocurre podes avisarme

2020-03-11 14:44 UTC, ignaciohug0g approved these changes

2020-03-12 15:33 UTC, merged